### ISSUE TITLE
Subtract mean value

### ISSUE THREAD

**Issue by hytseng0509** [DavideA/c3d-pytorch#4]
Hi,

Do we have to subtract the mean before the predicting?
Thanks for the sharing. =)

**Comment by tracer9** [comment]
Hi, @hytseng0509 , I checked the caffe implementation. Since caffe use OpenCV, so the image is : 

- [0, 255]
- BGR mode
- mean sub-straction. 

The implementation here use a skimage library. Input image is:
- [0, 255]
- RGB mode
- non-substraction

So you need first substraction the mean value according to each channel; then transfer RGB to BGR mode.

A sample code for reference:

>  X = get_sport_clip('roger')
    X = Variable(X)
    X.data[:, 0, :, :, :] -= 122.6   # R channel
    X.data[:, 1, :, :, :] -= 116.6   # G channel
    X.data[:, 2, :, :, :] -= 104.0   # B channel
    X = X[:, [2,1,0], :, :, :]   # channel swap
    X = X.cuda()

According to experiment, the difference is really small.

**Comment by hytseng0509** [comment]
Thanks for the information!

**Comment by apple2373** [comment]
I think this is ImageNet mean. It's true that we should subtract mean but we should use the mean from Sports1M.
