### ISSUE TITLE
Video -coding

### ISSUE THREAD

**Issue by CSer-Tang-hao** [DavideA/c3d-pytorch#7]
Hello, I'm new to this job, your code use frame image after cutting through the ready-made model to forecast, I want to ask if there code that can directly predict the input video ? Thanks!

**Comment by DavideA** [comment]
Hi,
I'm not sure I understood your concern correctly.

My code concatenates 16 frames to build an input clip for the network. Thus, the C3D network predicts the class given a 16 frames video.

Hope this helps,
D

**Comment by CSer-Tang-hao** [comment]
@DavideA ,I mean, the code now is the input of 16 consecutive frames, and the output is a picture that integrates 16 frames together, and identifies the category.Is there a code can be directly input video, directly output its category

**Comment by DavideA** [comment]
@CSer-Tang-hao 
the input is a 16 frames clip, the output is a probability distribution over 487 possible classes.

I'm not sure what you mean by "a picture that integrates 16 frames together, and identifies the category". Can you please point out the lines of code you refer to?

D

**Comment by DavideA** [comment]
Closing.

**Comment by PHDPeter** [comment]
I think @CSer-Tang-hao  might be getting at how you would deploy this using something like a live camera stream, i.e. taking the first 16 frames (frames 0 to 16) outputting a category (the highest of the probability distribution over 487 possible classes) and then repeat this for the next set of frames (1-17 for example) so that you could have a consistent stream of input and outputs? 

I am guessing this is possible but would like to know myself the kind of performance you would expect from running the C3D in this way?
